image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/al9-cms

stages:
  - flake8
  - test
  - build-docs
  - pages  # aka publish to GitLab Pages (naming matters)
before_script:
  - sudo yum install -y python3 python3-pip python3-devel > /dev/null
  - sudo pip3 install pep8-naming > /dev/null
  - echo flake8 version `flake8 --version`

flake8:
  stage: flake8
  script:
    - flake8 --extend-ignore N806
  rules:
    - when: always

.test_template:
  stage: test
  tags:
    - cvmfs
  script:
    - bash install.sh
    - source environment.sh
    - cd example
    - python3 -m pepper.runproc example_processor.py test_config.json
  rules:
    - when: always
  artifacts:
    expire_in: 10 hours
    paths:
     - example/cutflows.json

test:lcg104:
  extends: .test_template
  variables:
    LCG_VERSION: "LCG_104"
    LCG_PLATFORM: "x86_64-el9-gcc11-opt"

test:lcg107a:
  extends: .test_template
  variables:
    LCG_VERSION: "LCG_107a"
    LCG_PLATFORM: "x86_64-el9-gcc14-opt"

build-docs:
  stage: build-docs
  tags:
    - cvmfs
  script:
    - bash install.sh
    - source environment.sh
    - python3 -m pip install --upgrade --upgrade-strategy eager --editable .[docs]
    - cd docs
    - make html
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'  # Always run on master branch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - docs/**/*
        - "*.md"
        - pepper/**/*.py
  artifacts:
    paths:
      - docs/_build/html


pages:
  stage: pages
  tags:
    - cvmfs
  dependencies:
    - build-docs
  script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
