[metadata]
name = pepper
version = 1.0
description = ParticlE Physics ProcEssoR

[options]
packages = find:
install_requires =
    coffea >= 0.7.13,< 2023
    awkward >= 1.7.0, < 2
    dask_jobqueue >= 0.8.3
    distributed >= 2024.7.0
    bokeh !=3.0.*,>=2.4.2
    scipy <= 1.15.3
    h5py
    hdf5plugin
    hist
    hjson
    correctionlib
    setuptools < 71
# Setuptools restriction due to this bug: https://github.com/scikit-hep/uproot5/issues/1259 - can be removed after switching to ak 2/uproot 5
    numba <= 0.61
# Numba restriction due to this bug: https://github.com/numba/numba/issues/10239#event-3583569837 - will hopefully be fixed in next version, then this could be changed to a veto on 0.62 (but check first)

[options.extras_require]
dev =
    pep8-naming
docs =
    sphinx
    sphinx-autodoc-typehints
    sphinx-rtd-theme
    sphinx_design
    sphinx-copybutton
    pydata-sphinx-theme

	
[flake8]
extend-ignore = N806
max-line-length = 120
exclude = 
    docs

[mypy]
ignore_missing_imports = True
